# Generated by Django 4.2.5 on 2023-09-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_name', models.CharField(max_length=30)),
                ('traffic_email', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('traffic_address', models.CharField(max_length=100)),
            ],
        ),
    ]
