# Generated by Django 4.2.5 on 2023-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=40)),
                ('user_id', models.CharField(max_length=20)),
                ('user_phonenumber', models.CharField(max_length=14)),
                ('user_address', models.CharField(max_length=100)),
            ],
        ),
    ]
