# Generated by Django 4.2.5 on 2023-09-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_name', models.CharField(max_length=30)),
                ('employe_number', models.IntegerField()),
                ('employe_email', models.CharField(max_length=40)),
                ('employe_id', models.IntegerField()),
                ('employe_position', models.CharField(max_length=30)),
            ],
        ),
    ]
