# Generated by Django 4.2.5 on 2023-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_name', models.CharField(max_length=20)),
                ('Brand_name', models.CharField(max_length=20)),
                ('Realesed_date', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
            ],
        ),
    ]
